### ISSUE TITLE
Наповніть файл index.html

### ISSUE THREAD

**Issue by Dexter19** [sazafik/sazafik.github.io#1]
Ваш файл index.html пустий. Наповніть його згідно Т.З.

**Comment by sazafik** [comment]
Доброго Дня.
Ось
https://github.com/sazafik/sazafik.github.io/blob/main/exercises/lecture-02/index.html

сб, 3 февр. 2024 г. в 11:10, Nick ***@***.***>:

**Comment by sazafik** [comment]
Рішення
Exercises for lecture #1
https://github.com/sazafik/sazafik.github.io/blob/main/index.html
[image: image.png]

Exercises for lecture #2
https://github.com/sazafik/sazafik.github.io/blob/main/exercises/lecture-02/index.html
[image: image.png]


сб, 3 февр. 2024 г. в 11:31, Дмитро Вороненко ***@***.***>:

**Comment by sazafik** [comment]
Тут ще щось потрібно дороблювати?

**Comment by Dexter19** [comment]
Доброго дня!) Ні, у вас закриті 1, 2, 3 ДЗ
Сьогодні- завтра перевірятиму наступні.

**Comment by sazafik** [comment]
Це Добре. Дякую.
