### ISSUE TITLE
Дз -5 правки

### ISSUE THREAD

**Issue by Dexter19** [sazafik/sazafik.github.io#4]
@import url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css");
Перемістить в файл  css/main.css вашого персонального сайту

**Comment by Dexter19** [comment]
+ не побачив файл css/common.css Персонального сайту. 
Створи його і внеси в нього зміни як в ТЗ

**Comment by sazafik** [comment]
Виправив.
