### ISSUE TITLE
Правки до ДЗ 8

### ISSUE THREAD

**Issue by Dexter19** [sazafik/sazafik.github.io#6]
3. Обчислити ширину і висоту елемента .first-box
 Розпишіть в коментарях в кожному пункті як вираховували, ось приклад:
.first-box {
  width: 200px;
  height: 100px;
  border: 8px solid blue;
  padding: 20px;
  background: yellow;
  /* Total width: 200px + (2 * 20px) + (2 * 8px) = 256px
     Total height: 100px + (2 * 20px) + (2 * 8px) = 156px */
}
----------------------------------------------------------------
8. Є заголовок з властивістю display: inline-block, який потрібно розбити на два рядки. Його ширина має бути динамічною.
 Можемо поставити ось так
  h1 span {
      width: min-content;
      display: inline-block;
  }
-----------------------------------------------------------------

**Comment by sazafik** [comment]
Виправив. На гіт перезалив
