### ISSUE TITLE
Правки ДЗ 11

### ISSUE THREAD

**Issue by Dexter19** [sazafik/sazafik.github.io#7]
/*створити grid-контейнер з трьох рядків висотою 90px 300px 1fr і чотирьох стовпців однакової ширини
        main {
            display: grid;
            grid-template-rows: 90px 300px 1fr;
            grid-template-columns: repeat(4, 1fr);
            
        }*/
Тут треба записати ось так:
main {
  display: grid;
  grid-template-rows: 90px 300px 1fr;
  grid-template-columns: auto auto auto auto;
}
------------------------------------------------------------
 /*призначте рівномірні відстані до обох кінців grid-контейнера та між стовпцями
        main {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            justify-content: space-between;
            
        }*/
Тут запис маэ бути такий:
main {
  display: grid;
  justify-content: space-evenly;
  grid-template-columns: repeat(4, 50px);
}
---------------------------------------

**Comment by sazafik** [comment]
Привіт. Дякую.Виправив. На github Залив.
