### ISSUE TITLE
Уточнення ДЗ 12

### ISSUE THREAD

**Issue by Dexter19** [sazafik/sazafik.github.io#8]
Використовуючи функції clamp() та calc(), розрахуйте font-size, дотримуючись таких вимог:
Якщо ширина вікна перегляду становить 768 пікселів, розмір шрифту має дорівнювати 20 пікселям
Якщо ширина вікна перегляду перевищує 768 пікселів, розмір шрифту масштабується пропорційно
При 1920 пікселях розмір шрифту має дорівнювати 36 пікселями
Для екранів, менших за 768 пікселів, розмір шрифту не має бути меншим за 16 пікселів
Для екранів, розмір яких перевищує 1920 пікселів, розмір шрифту не має перевищувати 48 пікселів

Оптимальний запис для цієї задачі:
font-size: clamp(16px, calc(20px + (36 - 20) * (100vw - 768px)/(1920 - 768)), 48px);
--------------------------------------------------------------------------------------

**Comment by sazafik** [comment]
Дякую. Виправив і перезалив на гітхаб.
