### ISSUE TITLE
Правки до ДЗ 17

### ISSUE THREAD

**Issue by Dexter19** [sazafik/sazafik.github.io#9]
Пункт 2 Визначити результат наступних логічних виразів
У вас запис такий
let x = 3;
let y = 4;
let z = 5;

x ||= y; //x = 3
x || (y = z); true
x &&= y; // x останется 3, и y не изменится.
x && (y = z); //5
x ??= y;//3
x ?? (y = z); // x=3 y =4

Має бути так:
let x = 3;
let y = 4;
let z = 5;

x ||= y; // 3
x || (y = z); // 3
x &&= y; // 4
x && (y = z); // 5
x ??= y; // 4
x ?? (y = z); // 4

Перепровірте і зрозумійте чому так.
--------------------------------------
function checkNumber(num) {
    if (num === 3) {
        console.log("Поздравляем, вы сделали это!");
    } else if (num > 3) {
        console.log("Число слишком длинное");
    } else {
        console.log("Число слишком короткое");
    }
}

Тут як варіант можна зробити таким чином:
const number = 3;

let guess = prompt("Guess the number")
if (+guess > number) {
  alert('The number is too long');
} else if (+guess < number) {
  alert('The number is short');
}
else {
  alert('Congratulations, You did it!');
}

**Comment by sazafik** [comment]
Привіт.
Дякую.
Виправив та перезалив.
